import { describe, expect, it } from "vitest";

import * as runtime from "./index.js";

describe("runtime public API", () => {
  it("exports the audit, connection, command protocol, immutable entity, corpus, schema, and error foundation", () => {
    expect(Object.keys(runtime).sort()).toEqual([
      "ActorDraftSchema",
      "ActorKindSchema",
      "ActorSchema",
      "AuditEventDraftSchema",
      "AuditEventNameSchema",
      "AuditEventSchema",
      "CandidateChannelSchema",
      "CandidateDocumentDraftSchema",
      "CandidateDocumentSchema",
      "CandidateDraftSchema",
      "CandidateSchema",
      "CommandConflictReasonSchema",
      "CommandEnvelopeSchema",
      "CommandExecutionMetadataSchema",
      "CommandNameSchema",
      "CommandReceiptSchema",
      "CommandStatusSchema",
      "CorpusManifestContentMemberDocumentSchema",
      "CorpusManifestContentMemberSchema",
      "CorpusManifestContentSchema",
      "CorpusManifestDraftSchema",
      "CorpusManifestKindSchema",
      "CorpusManifestSchema",
      "CorpusManifestSealDraftSchema",
      "CorpusManifestSealSchema",
      "CorpusMemberDocumentDraftSchema",
      "CorpusMemberDocumentSchema",
      "CorpusMemberDraftSchema",
      "CorpusMemberSchema",
      "CorpusTagSchema",
      "DocumentKindSchema",
      "MAIN_DEMO_CORPUS_MEMBER_COUNT",
      "MAXIMUM_DOCUMENTS_PER_CANDIDATE",
      "MAXIMUM_DOCUMENTS_PER_CORPUS_MEMBER",
      "MAXIMUM_NORMALIZED_DOCUMENT_BYTES",
      "MAXIMUM_NORMALIZED_DOCUMENT_LENGTH",
      "MAXIMUM_RAW_DOCUMENT_BYTES",
      "RuntimeDatabaseOptionsSchema",
      "RuntimeErrorSchema",
      "SYSTEM_ACTOR_ID",
      "SourceDocumentDraftSchema",
      "SourceDocumentSchema",
      "SqliteConfigurationSchema",
      "actors",
      "appendAuditEvent",
      "auditEvents",
      "candidateDocuments",
      "candidates",
      "commandReceipts",
      "corpusManifestSeals",
      "corpusManifests",
      "corpusMemberDocuments",
      "corpusMembers",
      "createRuntimeError",
      "executeCommand",
      "hashCorpusManifestContent",
      "insertActor",
      "insertCandidate",
      "insertCandidateDocument",
      "insertCorpusManifest",
      "insertCorpusManifestSeal",
      "insertCorpusMember",
      "insertCorpusMemberDocument",
      "insertSourceDocument",
      "openRuntimeDatabase",
      "prepareActor",
      "prepareAuditEvent",
      "prepareCandidate",
      "prepareCandidateDocument",
      "prepareCorpusManifest",
      "prepareCorpusManifestSeal",
      "prepareCorpusMember",
      "prepareCorpusMemberDocument",
      "prepareSourceDocument",
      "readActor",
      "readAuditEvent",
      "readCandidate",
      "readCandidateDocument",
      "readCorpusManifest",
      "readCorpusManifestSeal",
      "readCorpusMember",
      "readCorpusMemberDocument",
      "readSourceDocument",
      "requirements",
      "roles",
      "rubricDimensions",
      "rubrics",
      "runImmediateTransaction",
      "runtimeMigrationSmoke",
      "sourceDocuments",
      "validateCorpusManifestContent"
    ]);
  });

  it("creates errors with optional safe details", () => {
    expect(
      runtime.createRuntimeError("migration_required", "Migration required", false, {
        schemaVersion: 0
      })
    ).toEqual({
      code: "migration_required",
      message: "Migration required",
      retryable: false,
      details: { schemaVersion: 0 }
    });
  });
});
